export default {
  products: [
    {
      id: 1,
      name: "Men & Women Shirt",
      price: 20,
      description: "Jesus",
      image: "../image/yexusheart.jpg",
    },
    {
      id: 2,
      name: "Men & Women Shirt Shirt",
      price: 20,
      description: "Customize name shirt",
      image: "../image/boy-shirt-name.jpg",
    },
    {
      id: 3,
      name: "Men Shirt",
      price: 15,
      description: "Jesus Shirt",
      image: "../image/JesusGrayShirt.jpg",
    },
    {
      id: 4,
      name: "Men & Women Shirt Gray Hoodie",
      price: 30,
      description: "Autism",
      image: "../image/hoodie_autism.jpg",
    },
    {
      id: 5,
      name: "Men & Women Shirt Navy Shirt",
      price: 20,
      description: "Customize name shirt",
      image: "../image/navyblueshirt.jpg",
    },
    {
      id: 6,
      name: " Women Shirt",
      price: 20,
      description: "Proverbs",
      image: "../image/proverbpeachcolorshirt.jpg",
    },
    {
      id: 7,
      name: "Women V-Neck Shirt",
      price: 20,
      description: "Jesus Cross",
      image: "../image/pinkv-neckshirt.jpg",
    },
    {
      id: 8,
      name: "Women Gray V-Neck Shirt",
      price: 20,
      description: "She is strong",
      image: "../image/shisstronggrayshirt.jpg",
    },
    {
      id: 9,
      name: "Women Shirt",
      price: 25,
      description: "Hmong Women",
      image: "../image/woman-shirt-logo.jpg",
    },
    {
      id: 10,
      name: "Men & Women Darkgray Shirt",
      price: 25,
      description: "Jesus Cross",
      image: "../image/jesuscrossgrayshirt.jpg",
    },
    {
      id: 11,
      name: "Women Sweater",
      price: 30,
      description: "BTS sweater",
      image: "../image/btssweater.jpg",
    },
    {
      id: 12,
      name: "Men & Women Gray Shirt",
      price: 25,
      description: "Hmong design",
      image: "../image/hmonglogograyshirt.jpg",
    },
  ],
};
