export default {
  hmongClothes: [
    {
      id: "h1",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h2",
      name: "Hmong women hat",
      price: 40,
      description: "Hmong women blue hat",
      image: "../image/hmong_hat1.jpg",
    },
    {
      id: "h3",
      name: "Hmong belt",
      price: 20,
      description: "Green front women belt",
      image: "../image/hmongBeltGreen.jpg",
    },
    {
      id: "h4",
      name: "Hmong women belt",
      price: 20,
      description: "Pink front women belt",
      image: "../image/hmongBeltPink.jpg",
    },
    {
      id: "h5",
      name: "Earring",
      price: 1,
      description: "Hmong women earrings",
      image: "../image/hmongEarring.jpg",
    },
    {
      id: "h6",
      name: "Earring",
      price: 1,
      description: "Hmong women earring",
      image: "../image/hmongEarring2.jpg",
    },
    {
      id: "h7",
      name: "Earring",
      price: 1,
      description: "Hmong women earring",
      image: "../image/hmongEarring3.jpg",
    },
    {
      id: "h8",
      name: "Hmong women hat",
      price: 40,
      description: "Hmong gold hat",
      image: "../image/hmongHatGold.jpg",
    },
    {
      id: "h9",
      name: "Earring",
      price: 1,
      description: "Hmong women earring",
      image: "../image/hmongEarring4.jpg",
    },
    {
      id: "h10",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmongEarring5.jpg",
    },
    {
      id: "h11",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmongEarring6.jpg",
    },
    {
      id: "h12",
      name: "Hmong women hat",
      price: 100,
      description: "Hmong women gold hat",
      image: "../image/hmongHatGold2.jpg",
    },
  ],
};
