export default {
  hmongClothes: [
    {
      id: "h1",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h2",
      name: "Hmong women hat",
      price: 50,
      description: "Hmong women blue hat",
      image: "../image/hmong_hat1.jpg",
    },
    {
      id: "h3",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h4",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h5",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h6",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h7",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h8",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h9",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h10",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h11",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
    {
      id: "h12",
      name: "Hmong women clothes",
      price: 100,
      description: "Hmong Laos style clothes",
      image: "../image/hmong_clothes1.jpg",
    },
  ],
};
